require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe WorkflowStepPackagesController, type: :controller do
  before :each do
    @workflow = FactoryBot.create(:workflow, workflow_type: FactoryBot.create(:workflow_type))
    Role.create name: 'Contributor'
    @user = FactoryBot.create(:user)
    @user.add_role 'Contributor'
    @auth_headers = @user.create_new_auth_token
    request.headers.merge!(@auth_headers)
    @workflow = FactoryBot.create(:workflow, workflow_type: FactoryBot.create(:workflow_type))
    @workflow_step = FactoryBot.create(:workflow_step, workflow: @workflow)
    @workflow_package = FactoryBot.create(:workflow_package, workflow: @workflow)
  end
  # This should return the minimal set of attributes required to create a valid
  # WorkflowStepPackage. As you add validations to WorkflowStepPackage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {user_id: @user.id, workflow_step_id: @workflow_step.id, workflow_package_id: @workflow_package.id}
  }

  let(:invalid_attributes) {
    {user_id: nil, workflow_step_id: nil, workflow_package_id: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkflowStepPackagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      workflow_step_package = WorkflowStepPackage.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      workflow_step_package = WorkflowStepPackage.create! valid_attributes
      get :show, params: {id: workflow_step_package.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      workflow_step_package = WorkflowStepPackage.create! valid_attributes
      get :edit, params: {id: workflow_step_package.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WorkflowStepPackage" do
        expect {
          post :create, params: {workflow_step_package: valid_attributes}, session: valid_session
        }.to change(WorkflowStepPackage, :count).by(1)
      end

      it "redirects to the created workflow_step_package" do
        post :create, params: {workflow_step_package: valid_attributes}, session: valid_session
        expect(response).to redirect_to(WorkflowStepPackage.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {workflow_step_package: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {user_id: @user.id, workflow_step_id: @workflow_step.id, workflow_package_id: @workflow_package.id}
      }

      it "updates the requested workflow_step_package" do
        workflow_step_package = WorkflowStepPackage.create! valid_attributes
        put :update, params: {id: workflow_step_package.to_param, workflow_step_package: new_attributes}, session: valid_session
        workflow_step_package.reload
      end

      it "redirects to the workflow_step_package" do
        workflow_step_package = WorkflowStepPackage.create! valid_attributes
        put :update, params: {id: workflow_step_package.to_param, workflow_step_package: valid_attributes}, session: valid_session
        expect(response).to redirect_to(workflow_step_package)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        workflow_step_package = WorkflowStepPackage.create! valid_attributes
        put :update, params: {id: workflow_step_package.to_param, workflow_step_package: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested workflow_step_package" do
      workflow_step_package = WorkflowStepPackage.create! valid_attributes
      expect {
        delete :destroy, params: {id: workflow_step_package.to_param}, session: valid_session
      }.to change(WorkflowStepPackage, :count).by(-1)
    end

    it "redirects to the workflow_step_packages list" do
      workflow_step_package = WorkflowStepPackage.create! valid_attributes
      delete :destroy, params: {id: workflow_step_package.to_param}, session: valid_session
      expect(response).to redirect_to(workflow_step_packages_url)
    end
  end

end
