version: '2'
services:
  db:
    image: postgres:9.5.1
    environment:
      POSTGRES_PASSWORD: mysecretlocalpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: web_app
  sharedbox:
    image: busybox
    volumes:
      - /var/www
      - /var/run
  redis:
      image: redis
  proxy:
    image: agilesix/nginx:v1
    build:
      context: ./nginx
      dockerfile: Dockerfile # we mean the ./nginx/Dockerfile
    volumes:
      - ./logs:/var/log
    volumes_from:
      - sharedbox
    ports:
      - "8000:80"
    depends_on:
      - web
  web:
    image: agilesix/adpq2018_backend:latest
    build:
      context: ./web
      dockerfile: Dockerfile # we mean the ./puppies/Dockerfile
      args:
         DEVISE_SECRET_KEY: 50739611fb998e73b639c302fa88344a32bd17dc62b7e88749aa8a6cecf97780627be4b52544c6fafc1777826a53d8e10b3e93de3e9ae710037525e7c2d57a1d
    environment: &app_server_enviroment_vars
      CONTAINER_ROLE: 'app_server'
      RAILS_ENV: production
      MAX_THREADS: 2     # Puma threads,  watch out so you don't run out of DB connection pool
      WEB_CONCURRENCY: 1 # should match CPU of server
      SECRET_KEY_BASE: 19d07059ab81ff584bd8fd7be03ed765c63f5f4c3518d05f39b41c7152134e294b2f09cbf5d925045caab0ef6475862fc42c8e6b35d63e353a1472057e90f8c4
      DEVISE_SECRET_KEY: 50739611fb998e73b639c302fa88344a32bd17dc62b7e88749aa8a6cecf97780627be4b52544c6fafc1777826a53d8e10b3e93de3e9ae710037525e7c2d57a1d

      REL_DATABASE_PASSWORD: mysecretlocalpassword
      REL_DATABASE_USERNAME: postgres
      REL_DATABASE_DATABASE: web_app
      REL_DATABASE_HOST: db
      REL_DATABASE_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_ID: 0 # id of redis db
    volumes:
      - ./logs:/app/log
    volumes_from:
      - sharedbox
    links:
      - db
      - redis
  bg_worker:
    image: agilesix/adpq2018_backend:latest
    environment:
      <<: *app_server_enviroment_vars
      CONTAINER_ROLE: 'bg_worker'
      MAX_THREADS: 5  # Sidekiq threads,  watch out so you don't run out of DB connection pool
    volumes:
      - ./logs:/app/log
    volumes_from:
      - sharedbox
    links:
      - db
      - redis
    depends_on:
      - web
