version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/backend
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76

      - run:
          name: Start container
          command: docker-compose -f docker-compose-test.yml build

      - run:
          name: Run Rails unit tests
          command: docker-compose -f docker-compose-test.yml run web bundle exec rails db:migrate
          command: docker-compose -f docker-compose-test.yml run web bundle exec rspec

  deploy:
      docker:
        - image: docker:17.05.0-ce-git
      working_directory: ~/lightning-rails-docker
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Install dependencies
            command: |
              apk add --no-cache py-pip=9.0.0-r1
              pip install docker-compose
              pip install awsebcli

        - run:
            name: Build production and push image (only master)
            command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker-compose build
              docker-compose push

        - run:
            name: Set up for deploy
            command: |
              eb status
        - run:
            name: Deploy
            command: |
              eb deploy --verbose

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master