branch-defaults:
  master:
    environment: lightning-rails-docker-env
environment-defaults:
  lightning-rails-docker-env:
    branch: null
    repository: null
global:
  application_name: rails-docker
  branch: null
  default_ec2_keyname: UbuntuServerAMI
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Multi-container Docker
    running on 64bit Amazon Linux/2.8.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
