FROM circleci/ruby:2.3-browsers

RUN gem install bundler

# Preinstall gems. This will ensure that Gem Cache wont drop on code change
WORKDIR /tmp
ADD ./Gemfile Gemfile
ADD ./Gemfile.lock Gemfile.lock

RUN (bundle check || bundle install --without development)

ADD ./ /app
RUN sudo chown -R circleci:circleci /app/
WORKDIR /app
RUN (bundle check || bundle install --without development)

CMD bash script/start_server.sh
